### PR TITLE
typo, missing some ls

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Comment by ardavis** [comment]
:+1:  @locks, look into learning `git squash`, I recently learned it, and it's been helpful. It will allow you to combine both of those commits into a single one. :smile:

**Comment by locks** [comment]
I know of git squash, but I did all these changes in the web interface.

I can squash them later before merging :)

**Comment by ardavis** [comment]
Fair enough :smile_cat:

**Comment by locks** [comment]
There :dancers: 

Found out some more changes and squashed those too.

**Comment by locks** [comment]
Is this PR still relevant? Just noticed it's still open.

**Pull request closed without merging**
